[package]
name = "jockey"
description = "Easy command line parsing for Rust"
version = "0.2.1"
authors = ["Richard Wiedenh√∂ft <richard@wiedenhoeft.xyz>"]
license = "MIT"
repository = "https://github.com/richard-w/jockey"

[dependencies]
